## ----------------------------------
## ..:: App3 app in Arcadia UNIT ::..
## ----------------------------------
apiVersion: v1
kind: Service
metadata:
  name: arcadia-app3
  namespace: arcadia
  labels:
    app: arcadia-app3
spec:
  type: ClusterIP
  ports:
  - name: arcadia-app3-unit-80
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
      app: arcadia-app3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-app3-unit
  namespace: arcadia
  labels:
    app: arcadia-app3
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-app3
      version: v1
  template:
    metadata:
      labels:
        app: arcadia-app3
        version: v1
    spec:
      containers:
      - env:
        - name: service_name
          value: arcadia-app3-unit
        image: registry.f5-udf.com:5000/arcadia-app3:unit
        imagePullPolicy: Always
        name: arcadia-app3-unit
        ports:
        - containerPort: 8080
          protocol: TCP
